const SECRET = "55ChitChat";
const PORT = 8484;
const SALT=10;
const DATABASE_NAME="ChitChat";
const DATA_USER_NAME="postgres";
const DATABASE_PASSWORD="newPassword";
const DATABASE="postgres";
const DATABASE_HOST="localhost"
const JWT_EXPIRY=86400;
export default { SECRET,JWT_EXPIRY,PORT,SALT,DATABASE_NAME,DATA_USER_NAME,DATABASE_PASSWORD,DATABASE,DATABASE_HOST};
